FROM golang:1.24-alpine AS builder

WORKDIR /app
COPY . .
RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux go build -o /app/dist/gnotifier-server ./server

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/dist/gnotifier-server .
COPY server/config.json .

EXPOSE 8080
CMD ["./gnotifier-server", "-config", "config.json"] 